# Site settings
title: Mayday.US
email: info@mayone.us
description: "MayOne.US - SuperPAC to end all SuperPACs. Join our effort to win a Congress committed to reforming the influence of money in Politics."
url: "http://mayday.us"

# Build settings
markdown: kramdown
permalink: pretty

exclude: ["update-extern.sh"]
